name: Delete Branch After Merge

on:
    pull_request:
        types: [closed]

jobs:
    delete-branch:
        if: github.event.pull_request.merged == true && github.ref != 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Delete branch
              uses: dawidd6/action-delete-branch@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branches: ${{ github.event.pull_request.head.ref }}
